#!/bin/sh

# 单元测试 - 打包 - 默认配置启动

set -e

if [ $# -ne 1 ]
then
  echo "$0 TAG"
  echo "TAG default is 1.0-SNAPSHOT"
  TAG=1.0-SNAPSHOT
else
  TAG=$1
fi

APP_PATH=$(cd `dirname $0`/../; pwd)
APP_NAME=`echo $APP_PATH | awk -F "/" '{print $NF}'`
cd $APP_PATH
echo APP_NAME:$APP_NAME
echo APP_PATH:$APP_PATH

# 0. 删除旧应用
# docker stop $APP_NAME

# 1. 测试-打包
mvn clean package -Ddocker.build.skip=false -Ddocker.image.tag=$TAG
echo "test and build success, start new process now"

# 2. 启动程序, 下面为一行命令,行与行之间不能有注释,空格
# todo 待确定统一日志挂载目录-v
docker run \
 -e LOG_PATH_ROOT=./logs \
 -p 8080:8080 \
 harbor.dfocus.co/library/$APP_NAME.application:$TAG
