#!/bin/bash

# mybatis逆向生成工具

set -e

# 回到common工程目录
basepath=$(cd `dirname $0`; pwd)
cd $basepath/../common

mvn mybatis-generator:generate
## 覆盖原来mapper,po,example. 但不会覆盖xml文件,xml会追加
#mvn -Dmybatis.generator.overwrite=true mybatis-generator:generate
